#!/usr/bin/env python3

import subprocess
import sys
from os.path import join
from pathlib import Path

from patch_ops import make_patcher


if __name__ == '__main__':

    if len(sys.argv) < 3:
        print("usage: reset_rpaths OBJECT RPATH...")
        sys.exit(2)

    path = Path(sys.argv[1])
    if not path.exists():
        print(f"object {sys.argv[1]} does not exist")
        sys.exit(1)

    patcher = make_patcher(sys.argv[1])
    rpaths = patcher.list_rpaths()

#    print("old rpaths:")
#    for rpath in rpaths:
#        print("  " + rpath)
#
#    print("----")

    for old_rpath in rpaths:
        patcher.remove_rpath(old_rpath)

    for new_rpath in sys.argv[2:]:
        patcher.add_rpath(new_rpath)

    patcher = make_patcher(sys.argv[1])
    rpaths = patcher.list_rpaths()

#    print("new rpaths:")
#    for rpath in rpaths:
#        print("  " + rpath)
